/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/alert/Alert.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    FormClient: typeof import('./components/FormClient.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ListClient: typeof import('./components/ListClient.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
